# Generated by "nix run .#update", don't edit this file.
{
  version = "1.17.10b";
  src = fetchTarball {
    url = "https://github.com/zen-browser/desktop/releases/download/1.17.10b/zen.linux-x86_64.tar.xz";
    sha256 = "sha256:0qs5v9w0kfvbd7y3rh7hqw9hq34sz979rc62z69v8ikcp3m2dmfl";
  };
}
