# Generated by "nix run .#update", don't edit this file.
{
  version = "1.17.12b";
  src = fetchTarball {
    url = "https://github.com/zen-browser/desktop/releases/download/1.17.12b/zen.linux-x86_64.tar.xz";
    sha256 = "sha256:18a3xy3g6nxbm1pvsznjk68c0zvbzs6pka3y919ssvi2fb7hw2vi";
  };
}
