# Generated by "nix run .#update", don't edit this file.
{
  version = "1.17.11b";
  src = fetchTarball {
    url = "https://github.com/zen-browser/desktop/releases/download/1.17.11b/zen.linux-x86_64.tar.xz";
    sha256 = "sha256:07bwn2m26v19m6hybcw444ygyczvnxgvfjjqjpl7h9scninhm81v";
  };
}
